// config.js

const ACCRED_LIST = {
    "AFC COMPIEGNE": "https://www.instagram.com/999constantpl/",
    "COMPIEGNE": "https://www.instagram.com/999constantpl/",
    "FC VERSAILLES": "louis.desloge@fcversailles.com",
    "US CHANTILLY": "https://www.instagram.com/uschantilly/",
    "US ORLEANS": "https://orleansloiretfoot.com/contact/",
    "NANTERRE": "https://www.nanterre92.com/club/acces/accreditations-journalistes/",
    "C'CHARTRES MHB": "manon.bougard@ccmhb.fr",
    "CHARTRES FOOTBALL" : "https://cchartresfootball.com/about-us/contact/",
    "CHARTRES": "https://tally.so/r/obRDgO",
    "PARIS 92": "contact@paris92.fr",
    "CRETEIL US": "https://uschb.fr/infos-pratiques/presse/",
    "IVRY": "5800000@ffhandball.net",
    "FRANCAIS VOLANTS": "contact.hockey@francais-volants.org",
    "SASP - SAINT QUENTIN BASKET BALL_U21" : "https://www.linkedin.com/in/camille-christiaens-6a1839227/",
    "CHAMBRAY" : "antoine.recher@cthb.fr",
    "EVREUX" : "secretariat@almevreuxbasket.com",
    "VIMY" : "contact@usvimy.fr",
    "PARIS FC" : "https://parisfc.fr/presse/",
    "RACING CLUB FRANCE" : "https://www.instagram.com/racing_cff/",
    "BRETIGNY" : "csbfootball@orange.fr",
    "PARIS BASKETBALL_U21" : "https://www.instagram.com/parisbasketball.asso/",
    "TREMBLAY": "contact@tremblayhandball.com",
    "MASSY ESSONNE" : "https://mehb.fr/amateur-infos-pratiques/contact/",
    "PONTAULT-COMBAULT" : "5877029@ffhandball.net",
    "PARIS BASKETBALL" : "https://parisbasketball.com/contact/",
    "PARIS SAINT-GERMAIN HANDBALL" : "https://www.instagram.com/psghandassoofficiel/",
    "NANTERRE 92_U21" : "https://www.nanterre92.com/club/club/contact/",
    "SAINT QUENTIN BASKET" : "contact@sqbb.fr"
};

const CUSTOM_LOGOS = {
    "NEUILLY MARNE": "https://s1.static-footeo.com/uploads/sfcneuillysurmarne/logo__saedjl.png",
    "CROIX FIC": "https://static.wixstatic.com/media/07a98a_98b1039494fa4482bb23a77e832974b2~mv2.png",
    "RACING CLUB FRANCE" : "https://upload.wikimedia.org/wikipedia/fr/f/f4/RacingCFFootball-logoann%C3%A9es2010.svg",
    "AMIENS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/b/bf/Logo_Amiens_SC_-_2022.svg/1002px-Logo_Amiens_SC_-_2022.svg.png",
    "BASTIA" : "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e0/Logo_Sporting_Club_Bastia_2024.svg/1618px-Logo_Sporting_Club_Bastia_2024.svg.png",
    "COMPIEGNE" : "https://upload.wikimedia.org/wikipedia/commons/3/33/AFC_COMPIEGNE_PRINCIPAL.png",
    "SARCELLES" : "https://aassarcelles.fr/wp-content/uploads/2024/12/Logo-AAS-Sarcelles.png",
    "CREIL" : "https://upload.wikimedia.org/wikipedia/fr/a/ac/Logo_AFC_Creil.svg",
    "ST QUENTIN O." : "https://upload.wikimedia.org/wikipedia/fr/5/50/Logo_Olympique_Saint-Quentin_-_ancien.svg",
    "DRANCY" : "https://upload.wikimedia.org/wikipedia/fr/thumb/6/6b/Logo_JA_Drancy_2017.svg/1536px-Logo_JA_Drancy_2017.svg.png",
    "CHARTRES FOOTBALL" : "https://upload.wikimedia.org/wikipedia/fr/thumb/8/85/Logo_C%27Chartres_Football_2018.svg/960px-Logo_C%27Chartres_Football_2018.svg.png",
    "LE PAYS DU VALOIS US" : "https://uslpv.fr/wp-content/uploads/2025/01/Design-sans-titre-1.png",
    "CAEN" : "https://upload.wikimedia.org/wikipedia/fr/thumb/7/79/Logo_SM_Caen_2016.svg/1536px-Logo_SM_Caen_2016.svg.png", 
    "AJACCIO" : "https://upload.wikimedia.org/wikipedia/fr/thumb/7/73/Logo_Gaz%C3%A9lec_Football_Club_Ajaccio_2012.svg/1864px-Logo_Gaz%C3%A9lec_Football_Club_Ajaccio_2012.svg.png",
    "QUEVILLY" : "https://upload.wikimedia.org/wikipedia/fr/c/c3/Logo_US_Quevilly_Rouen_2018.svg",
    "PAYS DE CASSEL US" : "https://upload.wikimedia.org/wikipedia/fr/thumb/a/af/Logo_US_Pays_de_Cassel_-_2018.svg/2560px-Logo_US_Pays_de_Cassel_-_2018.svg.png",
    "F.C.BALAGNE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c1/Logo_FC_Balagne_-_2022.svg/1402px-Logo_FC_Balagne_-_2022.svg.png",
    "METZ FC" : "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/FC_Metz_2021_Logo.svg/1432px-FC_Metz_2021_Logo.svg.png",
    "PARIS SAINT-GERMAIN" : "https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/960px-Paris_Saint-Germain_Logo.svg.png",
    "LOSC" : "https://upload.wikimedia.org/wikipedia/fr/thumb/6/62/Logo_LOSC_Lille_2018.svg/1200px-Logo_LOSC_Lille_2018.svg.png",
    "PARIS FC" : "https://upload.wikimedia.org/wikipedia/fr/archive/d/db/20190512200040%21Logo_Paris_FC_2011.svg",
    "OLYMPIQUE LYONNAIS" : "https://upload.wikimedia.org/wikipedia/fr/a/a5/Logo_Olympique_Lyonnais_-_2022.svg",
    "MANTOIS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4e/Logo_FC_Mantois.svg/1375px-Logo_FC_Mantois.svg.png",
    "DUNKERQUE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/7/72/Logo_USL_Dunkerque_2025.svg/langfr-250px-Logo_USL_Dunkerque_2025.svg.png",
    "VIMY" : "https://upload.wikimedia.org/wikipedia/en/e/e4/US_Vimy_logo.png",
    "REIMS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/9/9f/Logo_Stade_de_Reims_-_2020.svg/1032px-Logo_Stade_de_Reims_-_2020.svg.png",
    "SAINT MAUR" : "https://upload.wikimedia.org/wikipedia/fr/9/96/VGA_St-Maur_FF_Logo.png",
    "MOLSHEIM" : "https://www.statsfootofeminin.fr/img/logo_esme.png",
    "LORIENT" : "https://upload.wikimedia.org/wikipedia/fr/1/1d/Logo_FC_Lorient_Bretagne-Sud.svg",
    "ORLEANS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/9/96/Logo_US_Orl%C3%A9ans_2011.svg/960px-Logo_US_Orl%C3%A9ans_2011.svg.png",
    "VENDEE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/0/01/Logo_VFCLRSY.png/960px-Logo_VFCLRSY.png",
    "BREQUIGNY" : "https://tournois.fcgm.fr/wp-content/uploads/2014/10/Logo_CPB_Brequigny-200x200.png",
    "CHARNAY" : "https://www.proballers.com/api/getTeamLogo?id=13378&width=400",
    "EVREUX" : "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4b/Logo_ALM_%C3%89vreux_Basket_-_2021.svg/2560px-Logo_ALM_%C3%89vreux_Basket_-_2021.svg.png",
    "POITIERS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/d/db/Logo_Poitiers_Basket_86_-_2018.svg/1200px-Logo_Poitiers_Basket_86_-_2018.svg.png",
    "SQBB": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/82/Logo_Saint-Quentin_Basket-Ball_-_2019.svg/1730px-Logo_Saint-Quentin_Basket-Ball_-_2019.svg.png",
    "LE PORTEL": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/da/Logo_ESSM_Le_Portel_C%C3%B4te_d%27Opale_-_2015.svg/960px-Logo_ESSM_Le_Portel_C%C3%B4te_d%27Opale_-_2015.svg.png",
    "POLE FRANCE": "https://upload.wikimedia.org/wikipedia/fr/1/13/Logo_P%C3%B4le_France_BB.png",
    "STADE FRANCAIS BASKET": "https://upload.wikimedia.org/wikipedia/commons/9/96/Logo_Stade_Fran%C3%A7ais_Basket_Fond_transparent_959x959.png",
    "LAMBOISIERES": "https://ascabasket.com/public/4168/upload/images/clubs-adverses/logo-lamboisieres-martin-basket_1.png",
    "STADE ROCHELAIS": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/33/Logo_Stade_Rochelais_Basket_-_2018.svg/1200px-Logo_Stade_Rochelais_Basket_-_2018.svg.png",
    "NANTERRE": "https://upload.wikimedia.org/wikipedia/fr/thumb/7/7e/Logo_Nanterre_92_-_2016.svg/1200px-Logo_Nanterre_92_-_2016.svg.png",
    "BOURG EN BRESSE": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f2/Logo_JL_Bourg_Basket_-_2017.svg/1050px-Logo_JL_Bourg_Basket_-_2017.svg.png",
    "BOURG BASKET": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f2/Logo_JL_Bourg_Basket_-_2017.svg/1050px-Logo_JL_Bourg_Basket_-_2017.svg.png",
    "LE MANS SCM": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/aa/Logo_Le_Mans_FC_-_2025.svg/960px-Logo_Le_Mans_FC_-_2025.svg.png",
    "PARIS BASKETBALL": "https://upload.wikimedia.org/wikipedia/fr/archive/4/41/20240917070337%21Logo_Paris_Basketball_-_2024.svg",
    "BASKET CLUB FRANCONVILLE": "https://cob-calais.fr/wp-content/uploads/2021/11/bc-franconville-plessis-bouchard-c78763eb1bd14e10aae508c39ff4f526s200x200.png",
    "COTE D'OPALE BASKET CALAIS": "https://upload.wikimedia.org/wikipedia/fr/f/f5/COB_Calais_2014.png",
    "ASA SCEAUX": "https://dagoba-boutiques-01.s3.amazonaws.com/vendor0939/images/0001210962/sceaux_logo_180--0-0--813f7d22-d923-4e57-9ba3-3cccdddf389f.png",
    "LA TRONCHE MEYLAN": "https://media.scorenco.com/media/image/club-logo-1708424981.25292.png",
    "TOULOUSE": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Logo-tmb-Toulouse-basket.png",
    "AS MONACO": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/ff/Logo_AS_Monaco_Basket.svg/1524px-Logo_AS_Monaco_Basket.svg.png",
    "LE MANS SARTHE BASKET": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Le_Mans_Sarthe_Basket_logo_nouveau.png/250px-Le_Mans_Sarthe_Basket_logo_nouveau.png",
    "ASVEL BASKET": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/bf/Logo_ASVEL_Lyon_Villeurbanne_-_2018.svg/330px-Logo_ASVEL_Lyon_Villeurbanne_-_2018.svg.png",
    "SEM ELAN CHALON": "https://upload.wikimedia.org/wikipedia/fr/c/c3/Logo_Elan_Chalon_2018.svg",
    "LIMOGES CSP": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Logo_CSP_VECTO.svg/langfr-250px-Logo_CSP_VECTO.svg.png",
    "SAINT-AMAND HAINAUT": "https://upload.wikimedia.org/wikipedia/fr/d/d1/Logo_Saint-Amand_Hainaut_Basket_%282020%29.png",
    "SLUC NANCY": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/3b/SLUC_Nancy_%28logo%29.svg/2048px-SLUC_Nancy_%28logo%29.svg.png",
    "JDA DIJON": "https://upload.wikimedia.org/wikipedia/commons/0/01/JDA_Dijon_Basket.png",
    "LANDERNEAU": "https://upload.wikimedia.org/wikipedia/fr/1/19/Logo_lbb_2018.png",
    "CHARLEVILLE" : "https://upload.wikimedia.org/wikipedia/fr/1/18/Logo_Olympique_Charleville_Prix_Ardenne_M%C3%A9tropole_-_2024.svg",
    "CHAMPAGNE" : "https://wp.champagne-basket-feminin.fr/wp-content/uploads/2021/06/cbf-logo.png",
    "ESCAUDAIN" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2kTm_by0tvVVnliDU99BFlnYnaj2CfvWliA&s",
    "VICHY" : "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f2/Logo_JA_Vichy_Basket_-_2023.svg/1200px-Logo_JA_Vichy_Basket_-_2023.svg.png",
    "CHAMBRAY": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/bd/Chambray_Touraine_Handball_logo_2018.svg/1200px-Chambray_Touraine_Handball_logo_2018.svg.png",
    "BESANCON": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/fc/ESBF_2019.png/1200px-ESBF_2019.png",
    "SAINT-MAUR": "https://upload.wikimedia.org/wikipedia/fr/e/e7/Stella_Saint-Maur_Handball_Logo.png",
    "TOULON": "https://upload.wikimedia.org/wikipedia/fr/b/b1/Logo_du_Toulon_M%C3%A9tropole_Var_Handball.png",
    "ST AMAND": "https://upload.wikimedia.org/wikipedia/fr/9/90/Saint-Amand_Handball_Logo.png",
    "STRASBOURG ACHENHEIM": "https://sp-ao.shortpixel.ai/client/to_auto,q_glossy,ret_img/https://www.placedeshalles.com/wp-content/uploads/2024/07/SATH.jpg",
    "PARIS 92": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/60/Paris_92.svg/1200px-Paris_92.svg.png",
    "SAMBRE AVESNOIS": "https://www.sportstrategies.com/wp-content/uploads/2022/05/1652438143745.png",
    "METZ HANDBALL": "https://upload.wikimedia.org/wikipedia/fr/e/e8/Metz_Handball_logo_2014.png",
    "CRETEIL": "https://i0.wp.com/uschb.fr/wp-content/uploads/2023/07/USCHB_Logo_2025.png?fit=1200%2C1200&ssl=1",
    "SARAN": "https://upload.wikimedia.org/wikipedia/fr/5/50/Logo_2019_Saran_Loiret_Handball.png",
    "IVRY": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/6d/US_Ivry_Handball_logo_2016.svg/960px-US_Ivry_Handball_logo_2016.svg.png",
    "PONTAULT-COMBAULT": "https://upload.wikimedia.org/wikipedia/fr/thumb/0/0d/Pontault-Combault_handball.svg/1783px-Pontault-Combault_handball.svg.png",
    "CERCLE SPORTIF VESULIEN": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_b52vv79c5gat4zRO42onxe1PaDkpGls4MA&s",
    "ELITE VAL-D'OISE": "https://upload.wikimedia.org/wikipedia/fr/0/01/LogoEVO.webp",
    "CERNAY/WATTWILLER": "https://www.cwh.fr/wp-content/uploads/2021/02/cropped-cernay_handball.png",
    "NANTES HBC": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b9/HBC_Nantes_2011_logo.svg/1149px-HBC_Nantes_2011_logo.svg.png",
    "C'CHARTRES": "https://pro.ccmhb.fr/public/images/logo.png",
    "CHARTRES" : "https://www.ccmbf.fr/Medias/logos/logo_ccbf/logocbf.png",
    "SELESTAT ALSACE": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a9/S%C3%A9lestat_Alsace_handball_2017.svg/1158px-S%C3%A9lestat_Alsace_handball_2017.svg.png",
    "TREMBLAY": "https://upload.wikimedia.org/wikipedia/fr/b/bc/Logo_du_Tremblay_Handball.png",
    "MASSY": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/40/Massy_Essonne_Handball_logo.png/250px-Massy_Essonne_Handball_logo.png",
    "ATHLETIC CLUB BOULOGNE": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a8/Athletic_Club_de_Boulogne-Billancourt_logo.svg/1200px-Athletic_Club_de_Boulogne-Billancourt_logo.svg.png",
    "COURNON D'AUVERGNE": "https://lnh.fr/medias/sports_teams/cournon-d-auvergne__logo__2023-2024.png",
    "OGC NICE COTE D'AZUR": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/91/Logo_OGC_Nice_Handball.svg/1200px-Logo_OGC_Nice_Handball.svg.png",
    "DUNKERQUE GRAND LITTORAL": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR47Lmq47kquHMkgKxQFuz7TYm8ksaSYcqZJA&s",
    "ANGERS": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d3/Logo_Angers_SCO_-_2021.svg/1720px-Logo_Angers_SCO_-_2021.svg.png",
    "PAU BILLERE": "https://upload.wikimedia.org/wikipedia/fr/9/98/Logo_du_Pau_Bill%C3%A8re_Handball_2024.png",
    "VALENCE" : "https://upload.wikimedia.org/wikipedia/fr/e/e5/Logo_du_Valence_Handball_%282019%29.png",
    "SARREBOURG MOSELLE SUD" : "https://upload.wikimedia.org/wikipedia/fr/2/2b/SarrebourgMoselleSud_logo2020.png",
    "MHSC" : "https://upload.wikimedia.org/wikipedia/commons/6/6a/Logo_-_Montpellier_H%C3%A9rault_Sport_Club_%28MHSC%29.png",
    "LE MANS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Logo_Le_Mans_FC_-_2010.svg/2048px-Logo_Le_Mans_FC_-_2010.svg.png",
    "HAVRE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e6/Logo_Havre_AC_2012.svg/999px-Logo_Havre_AC_2012.svg.png",
    "MONTROUGE" : "https://d1e67q5w736kt2.cloudfront.net/france/clubs/montrouge-fc-92.jpg",
    "MAINVILLIERS" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCHkbHqJut_c0jJaQAACeOLrKJtXwMGAQOJA&s",
    "LAVAL" : "https://upload.wikimedia.org/wikipedia/fr/thumb/3/3c/Logo_Stade_lavallois_MFC_2022.svg/1649px-Logo_Stade_lavallois_MFC_2022.svg.png",
    "BRETIGNY" : "https://www.csbretignyfootball.fr/wp-content/uploads/2023/02/cropped-cropped-LOGO-CSB-1.png",
    "BOULAZAC" : "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a8/Logo_Boulazac_Basket_Dordogne_-_2019.svg/1132px-Logo_Boulazac_Basket_Dordogne_-_2019.svg.png",
    "VILLENEUVE D'ASCQ": "https://upload.wikimedia.org/wikipedia/fr/e/eb/Logo_ESBVA_%282024%29.png",
    "SAINT DENIS" : "https://s2.static-footeo.com/uploads/rc-saintdenis/logo__sae954.png",
    "AUBERVILLIERS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b9/Logo_FCM_Aubervilliers_-_2024.svg/1200px-Logo_FCM_Aubervilliers_-_2024.svg.png",
    "ORVAULT":"https://www.orvault.fr/wp-content/uploads/2025/05/Logo-Com-Saison-2024-2025.png",
    "MONTBRISON" : "https://s2.static-footeo.com/uploads/as-savigneux-montbrison/logo__t1wiaz.png",
    "STRASBOURG" : "https://upload.wikimedia.org/wikipedia/fr/b/b0/Logo_SIG_Strasbourg_-_2015.svg",
    "GRAFFENSTADEN" : "https://upload.wikimedia.org/wikipedia/fr/b/b0/Logo_SIG_Strasbourg_-_2015.svg",
    "VERSAILLE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/6/6e/Logo_FC_Versailles_-_2022.svg/960px-Logo_FC_Versailles_-_2022.svg.png",
    "AULNOYE" : "https://www.proballers.com/api/getTeamLogo?id=13660&width=400",
    "RED STAR" : "https://upload.wikimedia.org/wikipedia/commons/b/bc/Logo_RedStarFC.png",
    "VALENCIENNES" : "https://upload.wikimedia.org/wikipedia/fr/thumb/a/ac/Logo_Valenciennes_FC.svg/1761px-Logo_Valenciennes_FC.svg.png",
    "EXEMPT" : "https://www.pngall.com/wp-content/uploads/5/Traffic-Signal-Stop-Sign-PNG-Free-Image.png",
    "ROUBAIX" : "https://rcrwf.football/wp-content/uploads/2024/11/logo-rcrwf-rond-ok.png",
    "FC ST LO" : "https://upload.wikimedia.org/wikipedia/fr/8/81/Logo_FC_Saint-L%C3%B4_Manche_-_2024.svg",
    "FC ROUEN" : "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c2/Logo_FC_Rouen_1899_-_2022.svg/1734px-Logo_FC_Rouen_1899_-_2022.svg.png",
    "FLEURY" : "https://upload.wikimedia.org/wikipedia/fr/thumb/6/61/Logo_FC_Fleury_91_-_2023.svg/1280px-Logo_FC_Fleury_91_-_2023.svg.png",
    "QRM" : "https://upload.wikimedia.org/wikipedia/fr/c/c3/Logo_US_Quevilly_Rouen_2018.svg",
    "ST BRIEUC" : "https://upload.wikimedia.org/wikipedia/fr/6/65/Logo_Stade_Briochin_2010.svg",
    "OLYMPIQUE MARSEILLE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/4/43/Logo_Olympique_de_Marseille.svg/1612px-Logo_Olympique_de_Marseille.svg.png",
    "BEAUVAIS" : "https://upload.wikimedia.org/wikipedia/fr/archive/7/72/20190520004038%21AS_Beauvais_Oise_logo.svg",
    "BLOIS" : "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b0/Logo_Blois_Football_41.svg/960px-Logo_Blois_Football_41.svg.png",
    "OL LYONNES" : "https://upload.wikimedia.org/wikipedia/fr/e/ec/Logo_OL_Lyonnes_2025.svg",
    "NICE" : "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b1/Logo_OGC_Nice_2013.svg/1644px-Logo_OGC_Nice_2013.svg.png",
    "SOCHAUX MONTB. FC": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5a/Logo_FC_Sochaux_Montb%C3%A9liard_2015.svg/500px-Logo_FC_Sochaux_Montb%C3%A9liard_2015.svg.png",
    "PARIS 13 ATLETICO": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/44/Logo_Paris_13_Atletico_2020.svg/3840px-Logo_Paris_13_Atletico_2020.svg.png",
    "EFC FREJUS ST RAPH": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/55/Logo_%C3%89FC_Fr%C3%A9jus_Saint-Rapha%C3%ABl_-_2020.svg/960px-Logo_%C3%89FC_Fr%C3%A9jus_Saint-Rapha%C3%ABl_-_2020.svg.png",
    "CHAMBLY OISE FC": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d9/Logo_FC_Chambly_Oise.svg/1280px-Logo_FC_Chambly_Oise.svg.png",
    "BOURGES FC": "https://upload.wikimedia.org/wikipedia/fr/a/a3/Logo_Bourges_Foot_18_-_2021.svg",
    "BOULOGNE S/MER USCO": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/99/Logo_US_Boulogne_CO_-_2025.svg/langfr-250px-Logo_US_Boulogne_CO_-_2025.svg.png",
    "DIJON FCO": "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c9/LogoDFCO.svg/1876px-LogoDFCO.svg.png",
    "ST PRYVE ST HILAIRE": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/41/Logo_Saint-Pryv%C3%A9_Saint-Hilaire_FC.svg/2048px-Logo_Saint-Pryv%C3%A9_Saint-Hilaire_FC.svg.png",
    "ST MAUR LUSITANOS": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/89/Logo_US_Lusitanos_Saint-Maur_2018.svg/2048px-Logo_US_Lusitanos_Saint-Maur_2018.svg.png",
    "ANDREZIEUX-BOUTHEON": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d1/Logo_Andr%C3%A9zieux-Bouth%C3%A9on_FC_2019.svg/960px-Logo_Andr%C3%A9zieux-Bouth%C3%A9on_FC_2019.svg.png",
    "ST ETIENNE": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/3e/AS_Saint-Etienne-logo_2022.svg/1643px-AS_Saint-Etienne-logo_2022.svg.png",
    "SAINT QUENTIN": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/82/Logo_Saint-Quentin_Basket-Ball_-_2019.svg/1730px-Logo_Saint-Quentin_Basket-Ball_-_2019.svg.png",
    "CHANTILLY US": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b2/Logo_US_Chantilly.svg/1200px-Logo_US_Chantilly.svg.png",
    "FC BORGO": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/ab/Logo_FC_Borgo_-_2020.svg/1059px-Logo_FC_Borgo_-_2020.svg.png",
    "FCVB": "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c2/Logo_FC_Villefranche_Beaujolais_2015.svg/1920px-Logo_FC_Villefranche_Beaujolais_2015.svg.png",
    "ISTRES FC": "https://upload.wikimedia.org/wikipedia/fr/b/b0/Logo_Istres_FC_-_2022.svg",
    "BERRI CHATEAUROUX": "https://upload.wikimedia.org/wikipedia/fr/9/95/Logo_Berrichonne_Ch%C3%A2teauroux_2017.svg",
    "PAU FC": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/fa/Logo_Pau_FC_-_2022.svg/1200px-Logo_Pau_FC_-_2022.svg.png",
    "EPINAL SAS": "https://upload.wikimedia.org/wikipedia/commons/8/88/Logo_SAS_Football_2021.png",
    "US ST MALO": "https://upload.wikimedia.org/wikipedia/commons/e/ef/Logo_US_Saint-Malo_-_2012.svg",
    "CLERMONT FOOT 63": "https://upload.wikimedia.org/wikipedia/fr/thumb/7/79/Logo_Clermont_Foot_63_2013.svg/1791px-Logo_Clermont_Foot_63_2013.svg.png",
    "CONCARNEAU US": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/33/Logo_US_Concarneau.svg/1730px-Logo_US_Concarneau.svg.png",
    "FC 93 BOBIGNY": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d7/Logo_Football_Club_93-2024.png/250px-Logo_Football_Club_93-2024.png",
    "NANCY ASNL": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/fd/Logo_AS_Nancy_Lorraine_2018.svg/960px-Logo_AS_Nancy_Lorraine_2018.svg.png",
    "FCLDSD": "https://upload.wikimedia.org/wikipedia/fr/thumb/7/7c/Logo_FC_Limonest_Dardilly_Saint_Didier_-_2021.svg/960px-Logo_FC_Limonest_Dardilly_Saint_Didier_-_2021.svg.png",
    "LE PUY F. 43 AUVERGN": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/88/Logo_Puy_Foot_43_Auvergne_2017.svg/1080px-Logo_Puy_Foot_43_Auvergne_2017.svg.png",
    "RC LENS": "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c5/Logo_RC_Lens.svg/1510px-Logo_RC_Lens.svg.png",
    "WASQUEHAL FOOTBALL": "https://upload.wikimedia.org/wikipedia/fr/thumb/2/29/Logo_Wasquehal_Football_-_2017.svg/960px-Logo_Wasquehal_Football_-_2017.svg.png",
    "THONON EVIAN GG FC": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/64/Logo_Thonon_%C3%89vian_Grand_Gen%C3%A8ve_FC_2020.svg/1764px-Logo_Thonon_%C3%89vian_Grand_Gen%C3%A8ve_FC_2020.svg.png",
    "GUINGAMP EA": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Logo_EA_Guingamp_2019.svg/1024px-Logo_EA_Guingamp_2019.svg.png",
    "ESTAC TROYES": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/ES_Troyes_AC.svg/1665px-ES_Troyes_AC.svg.png",
    "SC AUBAGNE AIR BEL": "https://upload.wikimedia.org/wikipedia/en/9/94/SC_Aubagne_Air_Bel_logo.png",
    "FBBP": "https://upload.wikimedia.org/wikipedia/fr/archive/f/f9/20220727005049%21Logo_Football_Bourg-en-Bresse_P%C3%A9ronnas_01_-_2015.svg",
    "FC D'ANNECY": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a3/Logo_FC_Annecy_-_2022.svg/1039px-Logo_FC_Annecy_-_2022.svg.png",
    "AS ST-PRIEST": "https://upload.wikimedia.org/wikipedia/fr/4/46/Logo_AS_St_Priest.svg",
    "FC DIEPPE": "https://upload.wikimedia.org/wikipedia/fr/3/38/Logo_FC_Dieppois.svg",
    "THIONVILLE LUSITANOS": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b0/Logo_US_Thionville-Lusitanos_-_2021.svg/960px-Logo_US_Thionville-Lusitanos_-_2021.svg.png",
    "AIX PROVENCE UNIVERSITE CLUB": "https://lnh.fr/medias/sports_teams/aix__logo__2025-2026.png",
    "NIMES USAM GARD": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5c/USAM_N%C3%AEmes_Gard_logo.svg/500px-USAM_N%C3%AEmes_Gard_logo.svg.png",
    "RODEZ AVEYRON": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/6a/Logo_Rodez_AF_2017.svg/500px-Logo_Rodez_AF_2017.svg.png",
    "BASKET CLUB MARITIME GRAVELINES": "https://upload.wikimedia.org/wikipedia/fr/5/56/Logo_BCM_Gravelines_Dunkerque_GL_-_2013.svg",
    "STE GENEVIEVE FC": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/83/Logo_Sainte_Genevi%C3%A8ve_Football_Club_-_2022.svg/960px-Logo_Sainte_Genevi%C3%A8ve_Football_Club_-_2022.svg.png?20240924030233",
    "NIMES OL": "https://1000logos.net/wp-content/uploads/2020/09/Nimes-Olympique-Logo.png",
    "DRAGUIGNAN VAR HANDBALL": "https://dvhb83.fr/wp-content/uploads/2022/12/logo_dvhb_head.png"
};

const STADIUM_COORDS = {
    "AAS SARCELLES": { lat: 48.995, lon: 2.380 },
    "AAS SARCELLES 21": { lat: 48.995, lon: 2.380 },
    "AFC COMPIEGNE": { lat: 49.406, lon: 2.812 },
    "AFC CREIL 21": { lat: 49.256, lon: 2.477 },
    "ALM EVREUX BASKET": { lat: 49.020, lon: 1.144 },
    "AMIENS SCF 2": { lat: 49.894, lon: 2.264 },
    "ASA SCEAUX": { lat: 48.777, lon: 2.296 },
    "BASKET CLUB FRANCONVILLE (BCF) - 1": { lat: 48.991, lon: 2.223 },
    "C CHARTRES FOOTBALL 23": { lat: 48.452, lon: 1.480 },
    "CHARTRES": { lat: 48.441, lon: 1.503 },
    "CS BRETIGNY FOOTBALL": { lat: 48.608, lon: 2.308 },
    "CS MAINVILLIERS": { lat: 48.441, lon: 1.464 },
    "JEANNE D'ARC DRANCY": { lat: 48.926, lon: 2.443 },
    "LE MANS SARTHE BASKET": { lat: 47.954, lon: 0.232 },
    "LE PAYS DU VALOIS US": { lat: 49.141, lon: 3.012 },
    "LOSC": { lat: 50.574, lon: 3.208 },
    "MANTOIS 78 FC": { lat: 48.979, lon: 1.706 },
    "MONTROUGE FC 92": { lat: 48.814, lon: 2.316 },
    "NANTERRE 92": { lat: 48.895, lon: 2.217 },
    "NEUILLY MARNE SFC": { lat: 48.882, lon: 2.535 },
    "PARIS BASKETBALL": { lat: 48.899, lon: 2.361 },
    "PARIS FC": { lat: 48.819, lon: 2.348 },
    "PARIS FC 21": { lat: 48.730, lon: 2.404 },
    "PARIS SAINT-GERMAIN": { lat: 48.841, lon: 2.253 },
    "PAYS DE CASSEL US": { lat: 50.716, lon: 2.538 },
    "POLE FRANCE": { lat: 48.835, lon: 2.454 },
    "QUEVILLY RM": { lat: 49.408, lon: 1.074 },
    "RACING CLUB FRANCE": { lat: 48.929, lon: 2.249 },
    "SAINT DENIS RC": { lat: 48.934, lon: 2.349 },
    "SAINT QUENTIN": { lat: 49.849, lon: 3.280 },
    "SAINT QUENTIN": { lat: 49.849, lon: 3.280 },
    "ST QUENTIN O.": { lat: 49.858, lon: 3.275 },
    "STADE DE REIMS": { lat: 49.293, lon: 4.053 },
    "STADE FRANCAIS BASKET": { lat: 48.844, lon: 2.254 },
    "ORLEANS": { lat: 47.839, lon: 1.932 },
    "VERSAILLES 78 FC": { lat: 48.805, lon: 2.138 },
    "VGA SAINT MAUR": { lat: 48.806, lon: 2.493 },
    "VIMY US": { lat: 50.375, lon: 2.808 },
    "STELLA": { lat: 48.804, lon: 2.483 }, 
    "CHAMBRAY": { lat: 47.339, lon: 0.708 },
    "PARIS 92": { lat: 48.825, lon: 2.274 }, 
    "PSG": { lat: 48.836, lon: 2.253 }, 
    "ELITE VAL-D'OISE": { lat: 48.990, lon: 2.221 }, 
    "TREMBLAY": { lat: 48.948, lon: 2.569 }, 
    "IVRY US": { lat: 48.812, lon: 2.392 }, 
    "CRETEIL": { lat: 48.776, lon: 2.450 }, 
    "PONTAULT-COMBAULT": { lat: 48.796, lon: 2.611 }, 
    "MASSY ESSONNE": { lat: 48.730, lon: 2.275 },
    "DRANCY" : { lat: 48.9262, lon: 2.4593 },
    "RED STAR": { lat: 48.9073, lon: 2.3413 }, 
    "FLEURY 91": { lat: 48.6145, lon: 2.3678 }, 
    "CHAMBLY OISE": { lat: 49.2274, lon: 2.2530 },
    "STADE DE REIMS": { lat: 49.2474, lon: 4.0252 }, 
    "ORLEANS US": { lat: 47.8443, lon: 1.9360 },
    "ST MAUR LUSITANOS": { lat: 48.8044, lon: 2.4832 }, 
    "CHANTILLY US": { lat: 49.1974, lon: 2.4571 }, 
    "FC ROUEN": { lat: 49.4122, lon: 1.0774 },
    "ST PRYVE ST HILAIRE": { lat: 47.8864, lon: 1.8675 }, 
    "PARIS 13 ATLETICO": { lat: 48.8236, lon: 2.3692 }, 
    "QRM": { lat: 49.4122, lon: 1.0774 }, 
    "BEAUVAIS OISE": { lat: 49.4344, lon: 2.1121 }, 
    "LE MANS FC": { lat: 47.9576, lon: 0.2244 }, 
    "AMIENS SCF": { lat: 49.8936, lon: 2.2633 },
    "MAINVILLIERS" : { lat: 48.4545, lon: 1.4524 }
};

const WEATHER_ICONS = {
    0: "☀️", // Ciel dégagé
    1: "🌤️", 2: "⛅", 3: "☁️", // Nuageux
    45: "🌫️", 48: "🌫️", // Brouillard
    51: "🌦️", 53: "🌦️", 55: "🌦️", // Bruine
    61: "🌧️", 63: "🌧️", 65: "🌧️", // Pluie
    71: "❄️", 73: "❄️", 75: "❄️", // Neige
    95: "⛈️", // Orage
};
